/* tslint:disable */

/**
 * Admin Permission API
 * API Permission V1
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type { VoloAbpHttpRemoteServiceValidationErrorInfo } from './volo-abp-http-remote-service-validation-error-info';
/**
 *
 *
 * @export
 * @interface VoloAbpHttpRemoteServiceErrorInfo
 */
export interface VoloAbpHttpRemoteServiceErrorInfo {
  /**
   * @type {string}
   * @memberof VoloAbpHttpRemoteServiceErrorInfo
   */
  code?: null | string;

  /**
   * @type {{ [key: string]: any; }}
   * @memberof VoloAbpHttpRemoteServiceErrorInfo
   */
  data?: { [key: string]: any } | null;

  /**
   * @type {string}
   * @memberof VoloAbpHttpRemoteServiceErrorInfo
   */
  details?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpHttpRemoteServiceErrorInfo
   */
  message?: null | string;

  /**
   * @type {Array<VoloAbpHttpRemoteServiceValidationErrorInfo>}
   * @memberof VoloAbpHttpRemoteServiceErrorInfo
   */
  validationErrors?: Array<VoloAbpHttpRemoteServiceValidationErrorInfo> | null;
}
