/* tslint:disable */

/**
 * Admin Permission API
 * API Permission V1
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type { VoloAbpPermissionManagementUpdatePermissionDto } from './volo-abp-permission-management-update-permission-dto';
/**
 *
 *
 * @export
 * @interface VoloAbpPermissionManagementUpdatePermissionsDto
 */
export interface VoloAbpPermissionManagementUpdatePermissionsDto {
  /**
   * @type {Array<VoloAbpPermissionManagementUpdatePermissionDto>}
   * @memberof VoloAbpPermissionManagementUpdatePermissionsDto
   */
  permissions?: Array<VoloAbpPermissionManagementUpdatePermissionDto> | null;
}
