/* tslint:disable */

/**
 * Admin Permission API
 * API Permission V1
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type { VoloAbpHttpRemoteServiceErrorInfo } from './volo-abp-http-remote-service-error-info';
/**
 *
 *
 * @export
 * @interface VoloAbpHttpRemoteServiceErrorResponse
 */
export interface VoloAbpHttpRemoteServiceErrorResponse {
  /**
   * @type {VoloAbpHttpRemoteServiceErrorInfo}
   * @memberof VoloAbpHttpRemoteServiceErrorResponse
   */
  error?: VoloAbpHttpRemoteServiceErrorInfo;
}
