/* tslint:disable */

/**
 * Admin Permission API
 * API Permission V1
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface VoloAbpIdentityIdentityUserCreateDto
 */
export interface VoloAbpIdentityIdentityUserCreateDto {
  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserCreateDto
   */
  email: string;

  /**
   * @type {{ [key: string]: any; }}
   * @memberof VoloAbpIdentityIdentityUserCreateDto
   */
  extraProperties?: { [key: string]: any } | null;

  /**
   * @type {boolean}
   * @memberof VoloAbpIdentityIdentityUserCreateDto
   */
  isActive?: boolean;

  /**
   * @type {boolean}
   * @memberof VoloAbpIdentityIdentityUserCreateDto
   */
  lockoutEnabled?: boolean;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserCreateDto
   */
  name?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserCreateDto
   */
  password: string;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserCreateDto
   */
  phoneNumber?: null | string;

  /**
   * @type {Array<string>}
   * @memberof VoloAbpIdentityIdentityUserCreateDto
   */
  roleNames?: Array<string> | null;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserCreateDto
   */
  surname?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserCreateDto
   */
  userName: string;
}
