/* tslint:disable */

/**
 * Admin Permission API
 * API Permission V1
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface VoloAbpUsersUserData
 */
export interface VoloAbpUsersUserData {
  /**
   * @type {string}
   * @memberof VoloAbpUsersUserData
   */
  email?: null | string;

  /**
   * @type {boolean}
   * @memberof VoloAbpUsersUserData
   */
  emailConfirmed?: boolean;

  /**
   * @type {{ [key: string]: any; }}
   * @memberof VoloAbpUsersUserData
   */
  extraProperties?: { [key: string]: any } | null;

  /**
   * @type {string}
   * @memberof VoloAbpUsersUserData
   */
  id?: string;

  /**
   * @type {boolean}
   * @memberof VoloAbpUsersUserData
   */
  isActive?: boolean;

  /**
   * @type {string}
   * @memberof VoloAbpUsersUserData
   */
  name?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpUsersUserData
   */
  phoneNumber?: null | string;

  /**
   * @type {boolean}
   * @memberof VoloAbpUsersUserData
   */
  phoneNumberConfirmed?: boolean;

  /**
   * @type {string}
   * @memberof VoloAbpUsersUserData
   */
  surname?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpUsersUserData
   */
  tenantId?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpUsersUserData
   */
  userName?: null | string;
}
