/* tslint:disable */

/**
 * Admin Permission API
 * API Permission V1
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface VoloAbpIdentityIdentityRoleUpdateDto
 */
export interface VoloAbpIdentityIdentityRoleUpdateDto {
  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityRoleUpdateDto
   */
  concurrencyStamp?: null | string;

  /**
   * @type {{ [key: string]: any; }}
   * @memberof VoloAbpIdentityIdentityRoleUpdateDto
   */
  extraProperties?: { [key: string]: any } | null;

  /**
   * @type {boolean}
   * @memberof VoloAbpIdentityIdentityRoleUpdateDto
   */
  isDefault?: boolean;

  /**
   * @type {boolean}
   * @memberof VoloAbpIdentityIdentityRoleUpdateDto
   */
  isPublic?: boolean;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityRoleUpdateDto
   */
  name: string;
}
