/* tslint:disable */

/**
 * Admin Permission API
 * API Permission V1
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type { VoloAbpPermissionManagementPermissionGrantInfoDto } from './volo-abp-permission-management-permission-grant-info-dto';
/**
 *
 *
 * @export
 * @interface VoloAbpPermissionManagementPermissionGroupDto
 */
export interface VoloAbpPermissionManagementPermissionGroupDto {
  /**
   * @type {string}
   * @memberof VoloAbpPermissionManagementPermissionGroupDto
   */
  displayName?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpPermissionManagementPermissionGroupDto
   */
  displayNameKey?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpPermissionManagementPermissionGroupDto
   */
  displayNameResource?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpPermissionManagementPermissionGroupDto
   */
  name?: null | string;

  /**
   * @type {Array<VoloAbpPermissionManagementPermissionGrantInfoDto>}
   * @memberof VoloAbpPermissionManagementPermissionGroupDto
   */
  permissions?: Array<VoloAbpPermissionManagementPermissionGrantInfoDto> | null;
}
