/* tslint:disable */

/**
 * Admin Permission API
 * API Permission V1
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface VoloAbpPermissionManagementUpdatePermissionDto
 */
export interface VoloAbpPermissionManagementUpdatePermissionDto {
  /**
   * @type {boolean}
   * @memberof VoloAbpPermissionManagementUpdatePermissionDto
   */
  isGranted?: boolean;

  /**
   * @type {string}
   * @memberof VoloAbpPermissionManagementUpdatePermissionDto
   */
  name?: null | string;
}
