/* tslint:disable */

/**
 * Admin Permission API
 * API Permission V1
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type { VoloAbpPermissionManagementProviderInfoDto } from './volo-abp-permission-management-provider-info-dto';
/**
 *
 *
 * @export
 * @interface VoloAbpPermissionManagementPermissionGrantInfoDto
 */
export interface VoloAbpPermissionManagementPermissionGrantInfoDto {
  /**
   * @type {Array<string>}
   * @memberof VoloAbpPermissionManagementPermissionGrantInfoDto
   */
  allowedProviders?: Array<string> | null;

  /**
   * @type {string}
   * @memberof VoloAbpPermissionManagementPermissionGrantInfoDto
   */
  displayName?: null | string;

  /**
   * @type {Array<VoloAbpPermissionManagementProviderInfoDto>}
   * @memberof VoloAbpPermissionManagementPermissionGrantInfoDto
   */
  grantedProviders?: Array<VoloAbpPermissionManagementProviderInfoDto> | null;

  /**
   * @type {boolean}
   * @memberof VoloAbpPermissionManagementPermissionGrantInfoDto
   */
  isGranted?: boolean;

  /**
   * @type {string}
   * @memberof VoloAbpPermissionManagementPermissionGrantInfoDto
   */
  name?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpPermissionManagementPermissionGrantInfoDto
   */
  parentName?: null | string;
}
