/* tslint:disable */

/**
 * Admin Permission API
 * API Permission V1
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface VoloAbpPermissionManagementProviderInfoDto
 */
export interface VoloAbpPermissionManagementProviderInfoDto {
  /**
   * @type {string}
   * @memberof VoloAbpPermissionManagementProviderInfoDto
   */
  providerKey?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpPermissionManagementProviderInfoDto
   */
  providerName?: null | string;
}
