/* tslint:disable */

/**
 * Admin Permission API
 * API Permission V1
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface VoloAbpIdentityIdentityUserDto
 */
export interface VoloAbpIdentityIdentityUserDto {
  /**
   * @type {number}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  accessFailedCount?: number;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  concurrencyStamp?: null | string;

  /**
   * @type {Date}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  creationTime?: Date;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  creatorId?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  deleterId?: null | string;

  /**
   * @type {Date}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  deletionTime?: Date | null;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  email?: null | string;

  /**
   * @type {boolean}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  emailConfirmed?: boolean;

  /**
   * @type {number}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  entityVersion?: number;

  /**
   * @type {{ [key: string]: any; }}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  extraProperties?: { [key: string]: any } | null;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  id?: string;

  /**
   * @type {boolean}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  isActive?: boolean;

  /**
   * @type {boolean}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  isDeleted?: boolean;

  /**
   * @type {Date}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  lastModificationTime?: Date | null;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  lastModifierId?: null | string;

  /**
   * @type {Date}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  lastPasswordChangeTime?: Date | null;

  /**
   * @type {boolean}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  lockoutEnabled?: boolean;

  /**
   * @type {Date}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  lockoutEnd?: Date | null;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  name?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  phoneNumber?: null | string;

  /**
   * @type {boolean}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  phoneNumberConfirmed?: boolean;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  surname?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  tenantId?: null | string;

  /**
   * @type {string}
   * @memberof VoloAbpIdentityIdentityUserDto
   */
  userName?: null | string;
}
