/* tslint:disable */
/**
 * Admin Custom API
 * API Custom V1
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type { AxiosInstance, AxiosRequestConfig } from 'axios';

// Some imports not used depending on template conditions
import { useAppConfig } from '@vben/hooks';

import globalAxios from 'axios';

import { Configuration } from './configuration';

const { abpUrl } = useAppConfig(import.meta.env, import.meta.env.PROD);

export const BASE_PATH = abpUrl.replace(/\/+$/, '');

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
  csv: ',',
  pipes: '|',
  ssv: ' ',
  tsv: '\t',
};

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
  options: AxiosRequestConfig;
  url: string;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
  protected configuration: Configuration | undefined;

  constructor(
    configuration?: Configuration,
    protected basePath: string = BASE_PATH,
    protected axios: AxiosInstance = globalAxios,
  ) {
    if (configuration) {
      this.configuration = configuration;
      this.basePath = configuration.basePath || this.basePath;
    }
  }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
  override name = 'RequiredError' as const;

  constructor(
    public field: string,
    msg?: string,
  ) {
    super(msg);
  }
}
